AWSTemplateFormatVersion: '2010-09-09'
Description: Mobile notification content shared resources
Resources:
  ContentLambdaContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration: { ScanOnPush: true }
      RepositoryName: mobile-notifications-content
      ImageTagMutability: IMMUTABLE

  LiveblogsLambdaContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration: { ScanOnPush: true }
      RepositoryName: mobile-notifications-liveblogs
      ImageTagMutability: IMMUTABLE

Outputs:
  ContentLambdaContainerRepositoryUri:
    Description: "Uri of the ECR repository for the content notification lambda"
    Value: !GetAtt ContentLambdaContainerRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-ContentLambdaContainerRepositoryUri
  ContentLambdaContainerRepositoryArn:
    Description: "ARN of the ECR repository for the content notification lambda"
    Value: !GetAtt ContentLambdaContainerRepository.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ContentLambdaContainerRepositoryArn
  LiveblogsLambdaContainerRepositoryUri:
    Description: "Uri of the ECR repository for the liveblogs notification lambda"
    Value: !GetAtt LiveblogsLambdaContainerRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-LiveblogsLambdaContainerRepositoryUri
  LiveblogsLambdaContainerRepositoryArn:
    Description: "ARN of the ECR repository for the liveblogs notification lambda"
    Value: !GetAtt LiveblogsLambdaContainerRepository.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LiveblogsLambdaContainerRepositoryUri