name: build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        cache: 'sbt'

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.AWS_ECR_ROLE }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Build and publish docker image
      run: |
        docker build --platform linux/amd64 -t mobile-notifications-content:dev .
        docker tag mobile-notifications-content:dev $NOTIFICATION_CONTENT_LAMBDA_REPOSITORY_URL:$BUILD_NUMBER
        docker push ${NOTIFICATION_LAMBDA_REPOSITORY_URL}:${BUILD_NUMBER}
      env:
        NOTIFICATION_CONTENT_LAMBDA_REPOSITORY_URL: ${{ secrets.NOTIFICATION_CONTENT_LAMBDA_REPOSITORY_URL }}
        BUILD_NUMBER: ${{ github.run_number }}

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}

    - name: Build and Test project, Assemble jar, copy to root dir
      run: |
        sbt compile test assembly
        cp target/scala*/mobile-notifications-content.jar .

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests
        path: target/test-reports/TEST-*.xml
        reporter: java-junit
        only-summary: 'false'
        fail-on-error: 'true'

    - name: AWS Auth
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
        aws-region: eu-west-1

    - name: Upload to riff-raff
      uses: guardian/actions-riff-raff@v2
      with:
        configPath: riff-raff.yaml
        projectName: Mobile::mobile-notifications-content
        buildNumberOffset: 466
        contentDirectories: |
          mobile-notifications-content:
          - mobile-notifications-content.jar
          mobile-notifications-content-cfn:
          - cfn.yaml
